### ISSUE TITLE
hpc-config-apply should be verbose by default when stdout is TTY

### ISSUE THREAD

**Issue by mehdid** [edf-hpc/hpc-config#3]
_From @rezib on February 28, 2017 8:53_

Currently, hpc-config-apply redirects all output to syslog by default. The `-v` flag must be given to get all outputs on the user TTY (stdout/stderr). As users generally want the output and syslog is used in corner cases (hpc-config-apply boot time service), the default should be the verbose mode. A `--syslog` parameter (or similar) should be added for the service.

_Copied from original issue: edf-hpc/puppet-hpc#112_

**Comment by mehdid** [comment]
_From @hmlth on March 1, 2017 9:43_

This behavior was a copy of the old init.calibre behavior. The default could change. I think there is a missing verbosity level with only errors and a one line summary at the end that could be suitable for a launch by clustershell.

**Comment by mehdid** [comment]
IMO, the best solution is to make the script detect if stdout is a TTY. In such cases, hpc-config-apply would be verbose by default. When stdout is not a TTY, hpc-config-apply uses syslog or other appropriate.

Thomas's proposal is another feature, and which I also think would be very welcome. I suggest to make another ticket for it though.

**Comment by mehdid** [comment]
_From @rezib on July 21, 2017 13:7_

> IMO,  the best solution is to make the script detect if stdout is a TTY. In such cases, hpc-config-apply would be verbose by default. When stdout is not a TTY, hpc-config-apply uses syslog or other appropriate.

Yes, i agree.

**Comment by nmeaux** [comment]
fixed

**Comment by rezib** [comment]
Fixed with 2bbe7a4.

**Comment by rezib** [comment]
Oops, reopen since it misses a word in the manpage, and eventually the command help.
